<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-12
 * Time: 09:26
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;
use think\Db;
use think\db\Where;

class SupplierTask extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_yd_supplier_task';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }

    //获取历史未领取的数量
    public function getTaskMsgNum($openid, $no_where_id = 0){
        $where = " openid = '{$openid}' and id != '{$no_where_id}' and ( (gift2 = 0 and week_day_count >= 2) or (gift3 = 0 and week_day_count >= 3) )";
        return Db::connect($this->database_config)->table($this->tableName)->where($where)->count();
    }

    //获取当前用户的领取金币列表
    public function getGoldRateLists($openid, $limit){
        $where = [
            ['openid', '=', $openid],
            ['status', '=', 1],
            ['week_day_count', '>', 0]
        ];
        return Db::connect($this->database_config)->table($this->tableName)->where($where)->order(['id'=>'desc'])->limit($limit[0], $limit[1])->select();
    }
}


