<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-12
 * Time: 09:26
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;
use think\Db;

class ShopGoods extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_ewei_shop_goods';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }

    /**
     * 根据条码获取商品详情
     * @param $goods_code
     * @param $supplier_id
     */
    public function getInfoByGoodsCode($goods_code, $supplier_id){
        $goods_info = Db::connect($this->database_config)
            ->field('g.id,g.title,g.goods_code,g.thumb,g.marketprice')
            ->table($this->tableName)
            ->alias('g')
            ->join('ims_yd_supplier_goods ysg', 'g.id = ysg.goods_id')
            ->where(['ysg.supplier_id'=>$supplier_id, 'goods_code'=>$goods_code])
            ->find();
        return $goods_info;
    }

    public function randSec($where = []){
        return Db::connect($this->database_config)->table($this->table)->where($where)->field(['id', 'title','thumb'])->order(['id'=>'desc'])->limit(2)->select();
    }

    public function getSkuChannelGoods($where = []){
        $goods = Db::connect($this->database_config)
                ->field(['g.id','g.title','g.thumb','g.sale_pirce','g.marketprice','g.skuid','IFNULL(cs.channel_count, 0) as channel_count'])
                ->table($this->tableName)
                ->alias('g')
                ->LeftJoin('ims_bb_city_sku cs', 'cs.sku_id = g.skuid')
                ->where($where)
                ->order('channel_count', 'desc')
                ->limit(6)
                ->select();
        return $goods;
    }

    //获取同分类下的商品
    public function getCateGoods($where, $limit){
        return Db::connect($this->database_config)->field(['id','title','thumb','sale_pirce','marketprice','skuid'])->table($this->tableName)->where($where)->limit($limit)->select();
    }

    //获取某一品牌下的所有在售商品id
    public function getBrandsGoods($brand_id){
        $where = [
            ['g.sup_id', '=', 461],
            ['g.deleted', '=', 0],
            ['is_activity', '=', 0],
            ['item.brand_id', '=', $brand_id]
        ];
        $goods = Db::connect($this->database_config)
                    ->field(['g.id','item.code_list_str'])
                    ->table($this->tableName)
                    ->alias('g')
                    ->join('ims_bb_sku sku', 'sku.id = g.skuid')
                    ->join('ims_bb_goods_item item', 'item.id = sku.goods_id')
                    ->where($where)
                    ->select();
        //dump($goods);die;
        return $goods;
    }

    //获取所有这些code的所属品牌的排名
    public function getBrandCustomRank($codes){
        if(empty($codes)){
            return [];
        }
        $where = [
            ['is_valid', '=', 1],
            ['code', 'in', $codes],
            ['code', '<>', '']
        ];
        $codes = Db::connect($this->database_config)->field(['code','brand','potential_id'])->table('ims_goods_code_info')->where($where)->group('code,potential_id')->select();
        return $codes;
    }

    //获取在售商品在code_info中的品牌
    public function getCodeInfoBrandByShopGoodsCodes($codes = []){
        if(empty($codes)){
            return '';
        }

        return Db::connect($this->database_config)->table('ims_goods_code_info')->where([['code', 'in', $codes], ['brand', '<>', '']])->value('brand');
    }
}


