<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-12
 * Time: 09:26
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;
use think\Db;

class ScanBuyCart extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_scanbuy_goods_cart';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }

    //清空购物车
    public function clearCart($where){
        return Db::connect($this->database_config)->table($this->tableName)->where($where)->delete();
    }

    //清空当前店铺中的购物车商品
    public function clearSuppCart($openid, $supplier_id){
        return $this->clearCart(['openid'=>$openid, 'supplier_id'=>$supplier_id]);
    }

    //清空其他店铺中的购物车商品
    public function clearCartOtherSup($openid, $supplier_id){
        $where = [
            ['openid', '=', $openid],
            ['supplier_id', '<>', $supplier_id]
        ];
        return $this->clearCart($where);
    }
}


