<?php
/**
 * 小票打印机
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-11
 * Time: 14:34
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;

class YunPrint extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_shop_print_config';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }
}

