<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-11
 * Time: 17:38
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;

class YunPrintList extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_shop_print_list';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }
}
