<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-12
 * Time: 09:26
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;
use think\Db;

class ScanBuy extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_scanbuy_scan_record';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }

    //更新扫码记录的扫码状态
    public function updateScanRecordStatus($openid, $supplier_id){
        $where = "(openid = '{$openid}' and status = 1 and supplier_id != {$supplier_id}) or (supplier_id = {$supplier_id} and invalidtime <= ".time().")";
        return $this->updateInfoPro($where, ['status'=>2]);
    }

    //更新当前用户所有失效的扫码状态
    public function updateAllScanRecordStatus($openid){
        $where = [
            ['openid', '=', $openid],
            ['status', '=', 1],
            ['invalidtime', '<=', time()]
        ];
        return $this->updateInfoPro($where, ['status'=>2]);
    }
}