<?php
/**
 * Created by zsl
 * Author: zsl
 * Date: 2019-08-12
 * Time: 09:26
 */
namespace app\api\model\ydxq;

use app\api\model\CommonMiniMallModel;

class ShopMemberCart extends CommonMiniMallModel
{
    protected $autoWriteTimestamp = true;
    protected $tableName = 'ims_ewei_shop_member_cart';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setTableName($this->tableName);
    }
}


